services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jemkins_home
    networks:
      - net
  centos:
    container_name: remote-host-cnt
    image: remote-host-img
    build:
      context: centos
    networks:
      - net
networks:
  net:
